name: Docker Build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
       echo "${{ secrets.DOCKERPASS }}" | docker login -u "${{ secrets.DOCKERUSER }}" --password-stdin
       echo ${{ secrets.GH_TOKEN }} | docker login https://docker.pkg.github.com -u spechlde --password-stdin
       docker build -t docker.pkg.github.com/spechlde/tgtlg/tgtlg:latest .
       docker push docker.pkg.github.com/spechlde/tgtlg/tgtlg:latest
       docker build -t spechlde/tgtlg:latest .
       docker push spechlde/tgtlg:latest
